import { promises as fs } from 'fs';
import * as path from 'path';

/**
 * Represents a parsed line from a .env file.
 * We preserve the original structure so comments and blanks survive merges.
 */
interface EnvLine {
  type: 'comment' | 'blank' | 'entry';
  raw: string;
  key?: string;
  value?: string;
}

function parseDotenv(content: string): EnvLine[] {
  const lines = content.split('\n');
  const result: EnvLine[] = [];

  for (const raw of lines) {
    const trimmed = raw.trim();
    if (trimmed.length === 0) {
      result.push({ type: 'blank', raw });
      continue;
    }
    if (trimmed.startsWith('#')) {
      result.push({ type: 'comment', raw });
      continue;
    }
    // Match KEY=VALUE, KEY="VALUE", KEY='VALUE'
    const match = raw.match(/^\s*([\w.-]+)\s*=\s*(.*)/);
    if (match) {
      const key = match[1];
      let value = match[2];
      // Strip surrounding quotes
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      result.push({ type: 'entry', raw, key, value });
    } else {
      // Unrecognized line — preserve as-is
      result.push({ type: 'comment', raw });
    }
  }
  return result;
}

function serializeDotenv(lines: EnvLine[]): string {
  return lines.map(l => l.raw).join('\n');
}

export interface InjectResult {
  written: number;
  skipped: string[];
  overwritten: string[];
  gitignoreWarning: boolean;
}

export async function injectSecrets(
  targetPath: string,
  secrets: Map<string, string>,
  merge: boolean = true,
  overwrite: boolean = false,
  template?: string
): Promise<number> {
  let existingContent = '';
  try {
    existingContent = await fs.readFile(targetPath, 'utf8');
  } catch (err: any) {
    if (err.code !== 'ENOENT') throw err;
    // Use template if provided, otherwise default header
    if (template) {
      existingContent = template;
    } else {
      existingContent = '# Generated by mcp-secret-server — do not commit\n';
    }
  }

  const parsed = parseDotenv(existingContent);
  const existingKeys = new Map<string, number>(); // key -> line index
  parsed.forEach((line, idx) => {
    if (line.type === 'entry' && line.key) {
      existingKeys.set(line.key, idx);
    }
  });

  let appended = 0;
  const newEntries: EnvLine[] = [];

  for (const [key, value] of secrets.entries()) {
    const escapedValue = value.replace(/"/g, '\\"');
    const formattedLine = `${key}="${escapedValue}"`;

    if (existingKeys.has(key)) {
      if (merge && !overwrite) {
        // Skip — preserve existing
        continue;
      }
      if (overwrite) {
        // In-place replacement preserving position
        const idx = existingKeys.get(key)!;
        parsed[idx] = { type: 'entry', raw: formattedLine, key, value };
        appended++;
        continue;
      }
    }

    newEntries.push({ type: 'entry', raw: formattedLine, key, value });
    appended++;
  }

  // Append new entries at the end with a section header
  if (newEntries.length > 0) {
    parsed.push({ type: 'blank', raw: '' });
    parsed.push({ type: 'comment', raw: `# Injected by mcp-secret-server at ${new Date().toISOString()}` });
    for (const entry of newEntries) {
      parsed.push(entry);
    }
  }

  if (appended > 0) {
    const finalContent = serializeDotenv(parsed);
    await fs.mkdir(path.dirname(targetPath), { recursive: true });
    await fs.writeFile(targetPath, finalContent, { mode: 0o600, encoding: 'utf8' });
  }

  return appended;
}

/**
 * Checks if the target .env path is covered by a .gitignore.
 * Walks up the directory tree looking in each .gitignore.
 */
export async function checkGitignore(targetPath: string): Promise<boolean> {
  const fileName = path.basename(targetPath);
  let dir = path.dirname(targetPath);
  const root = path.parse(dir).root;

  while (dir !== root) {
    try {
      const gitignorePath = path.join(dir, '.gitignore');
      const content = await fs.readFile(gitignorePath, 'utf8');
      if (content.includes(fileName) || content.includes('.env') || content.includes('*.env')) {
        return true;
      }
    } catch {
      // No .gitignore here, keep walking
    }
    dir = path.dirname(dir);
  }
  return false;
}
