import { injectSecrets, checkGitignore } from './dotenv-writer';
import { promises as fs } from 'fs';
import * as path from 'path';

describe('dotenv-writer Environment Merger', () => {
  const TEST_DIR = path.join(__dirname, '__test_fixtures__');
  const TEST_ENV = path.join(TEST_DIR, '.env');

  beforeEach(async () => {
    await fs.mkdir(TEST_DIR, { recursive: true });
  });

  afterEach(async () => {
    try {
      await fs.rm(TEST_DIR, { recursive: true, force: true });
    } catch (e) {}
  });

  it('writes new secrets to a new .env file with header', async () => {
    const secrets = new Map();
    secrets.set('NEW_API_KEY', 'sekret_value_123');

    const count = await injectSecrets(TEST_ENV, secrets);
    expect(count).toBe(1);

    const content = await fs.readFile(TEST_ENV, 'utf8');
    expect(content).toContain('Generated by mcp-secret-server');
    expect(content).toContain('NEW_API_KEY="sekret_value_123"');
  });

  it('merges new secrets and preserves existing keys and comments', async () => {
    await fs.writeFile(TEST_ENV, '# My project config\nEXISTING_KEY="old_value"\n# Important note\nDATABASE_URL="postgres://localhost"\n');

    const secrets = new Map();
    secrets.set('NEW_API_KEY', 'brand_new!');
    secrets.set('EXISTING_KEY', 'should_not_overwrite');

    const count = await injectSecrets(TEST_ENV, secrets, true, false);
    expect(count).toBe(1); // Only NEW_API_KEY

    const content = await fs.readFile(TEST_ENV, 'utf8');
    expect(content).toContain('EXISTING_KEY="old_value"'); // preserved
    expect(content).toContain('# My project config'); // comment preserved
    expect(content).toContain('# Important note'); // comment preserved
    expect(content).toContain('DATABASE_URL="postgres://localhost"'); // preserved
    expect(content).toContain('NEW_API_KEY="brand_new!"');
  });

  it('overwrites existing secrets in-place when overwrite is true', async () => {
    await fs.writeFile(TEST_ENV, '# Config\nEXISTING_KEY="old_value"\nOTHER_KEY="keep_me"\n');

    const secrets = new Map();
    secrets.set('EXISTING_KEY', 'new_value_overwritten');

    const count = await injectSecrets(TEST_ENV, secrets, true, true);
    expect(count).toBe(1);

    const content = await fs.readFile(TEST_ENV, 'utf8');
    expect(content).toContain('EXISTING_KEY="new_value_overwritten"');
    expect(content).not.toContain('old_value');
    expect(content).toContain('OTHER_KEY="keep_me"'); // untouched
    expect(content).toContain('# Config'); // comment preserved
  });

  it('uses template content when target does not exist', async () => {
    const template = '# Anthropic Template\nANTHROPIC_MODEL=claude-sonnet-4-20250514\n';
    const secrets = new Map();
    secrets.set('ANTHROPIC_API_KEY', 'sk-ant-xxx');

    const count = await injectSecrets(TEST_ENV, secrets, true, false, template);
    expect(count).toBe(1);

    const content = await fs.readFile(TEST_ENV, 'utf8');
    expect(content).toContain('# Anthropic Template');
    expect(content).toContain('ANTHROPIC_MODEL=claude-sonnet-4-20250514');
    expect(content).toContain('ANTHROPIC_API_KEY="sk-ant-xxx"');
  });

  it('escapes double quotes in values', async () => {
    const secrets = new Map();
    secrets.set('TRICKY_KEY', 'value_with_"quotes"_inside');

    const count = await injectSecrets(TEST_ENV, secrets);
    expect(count).toBe(1);

    const content = await fs.readFile(TEST_ENV, 'utf8');
    expect(content).toContain('TRICKY_KEY="value_with_\\"quotes\\"_inside"');
  });
});

describe('checkGitignore', () => {
  // Use /tmp to isolate from project .gitignore which includes .env
  const TEST_DIR = path.join('/tmp', `mcp-test-gitignore-${Date.now()}`);

  beforeEach(async () => {
    await fs.mkdir(TEST_DIR, { recursive: true });
  });

  afterEach(async () => {
    try {
      await fs.rm(TEST_DIR, { recursive: true, force: true });
    } catch (e) {}
  });

  it('returns true when .env is in .gitignore', async () => {
    await fs.writeFile(path.join(TEST_DIR, '.gitignore'), 'node_modules/\n.env\n');
    const result = await checkGitignore(path.join(TEST_DIR, '.env'));
    expect(result).toBe(true);
  });

  it('returns false when .env is NOT in .gitignore', async () => {
    await fs.writeFile(path.join(TEST_DIR, '.gitignore'), 'node_modules/\n');
    const result = await checkGitignore(path.join(TEST_DIR, '.env'));
    expect(result).toBe(false);
  });

  it('returns false when no .gitignore exists', async () => {
    const result = await checkGitignore(path.join(TEST_DIR, '.env'));
    expect(result).toBe(false);
  });
});
